apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: reports-core-api
  labels:
    app: reports-core-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reports-core-api
  template:
    metadata:
      labels:
        app: reports-core-api
        version: <REPORTS_API_VERSION>
    spec:
      containers:
      - name: reports-core-api
        image: gcr.io/r10c-general/reports-core-api:<REPORTS_API_VERSION>
        ports:
        - containerPort: 8095
---
apiVersion: v1
kind: Service
metadata:
  name: reports-core-api
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8095
  type: NodePort
  selector:
    app: reports-core-api
